stages:
  - lint
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
cache:
  paths:
    - .cache/
    - venv/

# backend-lint:
#   stage: lint
#   image: python:3.6
#   script:
#     - pip install pylint==1.9.2 --quiet
#     - pylint --rcfile=mmda-backend/.pylintrc

frontend-lint:
  stage: lint
  image: node:alpine
  allow_failure: true
  before_script:
    - cd mmda-frontend/
    - yarn install
  script:
    - yarn run lint

frontend-test:
  stage: test
  image: node:alpine
  before_script:
    - cd mmda-frontend/
    - yarn install
  script:
    - yarn run test:unit

backend-test:
  stage: test
  image: python:3.6
  before_script:
    - cd mmda-backend/
    - pip install --quiet -r requirements.txt
    - pipenv install --dev
  script:
    - py.test --cov-report term-missing -v --cov=backend/
