stages:
  - lint
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
cache:
  paths:
    - ~/.cache/pip/
    - ~/node_modules/

backend-lint:
  stage: lint
  image: python:3.6
  allow_failure: true
  script:
    - cd mmda-backend/
    - pip install pylint==1.9.2 --quiet
    - pylint --rcfile=.pylintrc backend/*/*.py

frontend-lint:
  stage: lint
  image: node:alpine
  allow_failure: true
  before_script:
    - cd mmda-frontend/
    - yarn install
  script:
    - yarn run lint

frontend-test:
  stage: test
  image: node:8-alpine
  before_script:
    - cd mmda-frontend/
    - yarn install
  script:
    - node --version; yarn --version
    - yarn run test:unit

backend-test:python3-6:
  stage: test
  image: python:3.6
  before_script:
    - python --version; pip --version
    - cd mmda-backend/
    - pip install --quiet -r requirements.txt
    - pipenv install --system --dev
  script:
    - pipenv run pytest --cov-report term-missing -v --cov=backend/

backend-test:python3-5:
  stage: test
  image: python:3.5
  allow_failure: true
  before_script:
    - python --version; pip --version
    - cd mmda-backend/
    - pip install --quiet -r requirements.txt
    - pipenv install --system --dev
  script:
    - pipenv run pytest -v

openapi-documentation:
  stage: build
  image: python:3.6
  before_script:
    - pip3 install --quiet pyyaml
  script:
    - python3 documentation/swagger-yaml-to-html.py < documentation/mmda-openapi.yaml > documentation/mmda.html
  artifacts:
    paths:
      - documentation/mmda.html
