stages:
  - lint
  - test
  - build

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache"
cache:
  paths:
    - ~/.cache/pip/
    - ~/node_modules/

backend-lint:
  stage: lint
  image: python:3.6
  script:
    - cd mmda-backend/
    - pip install pylint==1.9.2 --quiet
    - pylint --rcfile=.pylintrc backend/*/*.py

frontend-lint:
  stage: lint
  image: node:alpine
  allow_failure: true
  before_script:
    - cd mmda-frontend/
    - yarn install
  script:
    - yarn run lint

frontend-test:
  stage: test
  image: node:alpine
  before_script:
    - cd mmda-frontend/
    - yarn install
  script:
    - yarn run test:unit

backend-test:
  stage: test
  image: python:3.6
  before_script:
    - cd mmda-backend/
    - pip install --quiet -r requirements.txt
    - pipenv install --system --dev
    - cp backend/corpora_settings_example.py backend/corpora_settings_development.py
    - cp backend/local_settings_example.py backend/local_settings_development.py
  script:
    - pipenv run pytest --cov-report term-missing -v --cov=backend/
