version: '3'
services:
  mmda-backend:
    build:
      context: ./mmda-backend
      dockerfile: Dockerfile
    environment:
      - SQL_DATABASE_URI=sqlite:////var/local/mmda.sqlite
      - ENVIRONMENT=development
    ports:
      - '5000:5000'
  mmda-frontend:
    build:
      context: ./mmda-frontend
      dockerfile: Dockerfile
    depends_on:
      - mmda-backend
    links:
      - mmda-backend
    ports:
      - '8080:80'
      - '8443:443'
