version: '3'
services:
  mmda-backend:
    build:
      context: ./mmda-backend
      dockerfile: Dockerfile
    environment:
      - SQL_DATABASE_URI=sqlite:////var/local/mmda.sqlite
      - ENVIRONMENT=development
    # volumes:
    # Mount the pymagnitude files in the corpora_settings path
    #   - /local/pymagnitude.file:/docker/pymagnitude.file
    # For database persistence
    #   - /local/mmda.sqlite:/var/local/mmda.sqlite
    ports:
      - '5000:5000'
  mmda-frontend:
    build:
      context: ./mmda-frontend
      dockerfile: Dockerfile
    depends_on:
      - mmda-backend
    links:
      - mmda-backend
    ports:
      - '8080:80'
      - '8443:443'
