"""empty message

Revision ID: 35c3d26f9cc7
Revises: 855d3d896d74
Create Date: 2021-05-12 13:48:33.318433

"""

# revision identifiers, used by Alembic.
revision = '35c3d26f9cc7'
down_revision = '855d3d896d74'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('user_roles')
    op.drop_table('role')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('description', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_roles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('role_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False),
    sa.Column('reset_password_token', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('email_confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False),
    sa.Column('last_name', sa.VARCHAR(length=255), server_default=sa.text("('')"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###
